/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  QueryClient,
  QueryFunctionContext,
  QueryKey,
} from "@tanstack/react-query";
import { SpeakeasyCodeSamplesCore } from "../core.js";
import { codeSamplesGet } from "../funcs/codeSamplesGet.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
export type CodeSamplesQueryData = components.UsageSnippets;

export function prefetchCodeSamples(
  queryClient: QueryClient,
  client$: SpeakeasyCodeSamplesCore,
  request: operations.GetCodeSamplesRequest,
  options?: RequestOptions,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildCodeSamplesQuery(
      client$,
      request,
      options,
    ),
  });
}

export function buildCodeSamplesQuery(
  client$: SpeakeasyCodeSamplesCore,
  request: operations.GetCodeSamplesRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (context: QueryFunctionContext) => Promise<CodeSamplesQueryData>;
} {
  return {
    queryKey: queryKeyCodeSamples({
      registryUrl: request.registryUrl,
      operationIds: request.operationIds,
      methodPaths: request.methodPaths,
      languages: request.languages,
    }),
    queryFn: async function codeSamplesQueryFn(
      ctx,
    ): Promise<CodeSamplesQueryData> {
      const sig = combineSignals(
        ctx.signal,
        options?.signal,
        options?.fetchOptions?.signal,
      );
      const mergedOptions = {
        ...options?.fetchOptions,
        ...options,
        signal: sig,
      };

      return unwrapAsync(codeSamplesGet(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyCodeSamples(
  parameters: {
    registryUrl?: string | undefined;
    operationIds?: Array<string> | undefined;
    methodPaths?: Array<operations.MethodPaths> | undefined;
    languages?: Array<string> | undefined;
  },
): QueryKey {
  return ["@speakeasyapi/code-samples", "codeSamples", "get", parameters];
}
