/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { SpeakeasyCodeSamplesError } from "../models/errors/speakeasycodesampleserror.js";
import * as operations from "../models/operations/index.js";
import { useSpeakeasyCodeSamplesContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";
import {
  buildCodeSamplesQuery,
  CodeSamplesQueryData,
  prefetchCodeSamples,
  queryKeyCodeSamples,
} from "./codeSamples.core.js";
export {
  buildCodeSamplesQuery,
  type CodeSamplesQueryData,
  prefetchCodeSamples,
  queryKeyCodeSamples,
};

export type CodeSamplesQueryError =
  | errors.ErrorT
  | SpeakeasyCodeSamplesError
  | ResponseValidationError
  | ConnectionError
  | RequestAbortedError
  | RequestTimeoutError
  | InvalidRequestError
  | UnexpectedClientError
  | SDKValidationError;

/**
 * Retrieve usage snippets
 *
 * @remarks
 * Retrieve usage snippets from an OpenAPI document stored in the registry. Supports filtering by language and operation ID.
 */
export function useCodeSamples(
  request: operations.GetCodeSamplesRequest,
  options?: QueryHookOptions<CodeSamplesQueryData, CodeSamplesQueryError>,
): UseQueryResult<CodeSamplesQueryData, CodeSamplesQueryError> {
  const client = useSpeakeasyCodeSamplesContext();
  return useQuery({
    ...buildCodeSamplesQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * Retrieve usage snippets
 *
 * @remarks
 * Retrieve usage snippets from an OpenAPI document stored in the registry. Supports filtering by language and operation ID.
 */
export function useCodeSamplesSuspense(
  request: operations.GetCodeSamplesRequest,
  options?: SuspenseQueryHookOptions<
    CodeSamplesQueryData,
    CodeSamplesQueryError
  >,
): UseSuspenseQueryResult<CodeSamplesQueryData, CodeSamplesQueryError> {
  const client = useSpeakeasyCodeSamplesContext();
  return useSuspenseQuery({
    ...buildCodeSamplesQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function setCodeSamplesData(
  client: QueryClient,
  queryKeyBase: [
    parameters: {
      registryUrl?: string | undefined;
      operationIds?: Array<string> | undefined;
      methodPaths?: Array<operations.MethodPaths> | undefined;
      languages?: Array<string> | undefined;
    },
  ],
  data: CodeSamplesQueryData,
): CodeSamplesQueryData | undefined {
  const key = queryKeyCodeSamples(...queryKeyBase);

  return client.setQueryData<CodeSamplesQueryData>(key, data);
}

export function invalidateCodeSamples(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [parameters: {
      registryUrl?: string | undefined;
      operationIds?: Array<string> | undefined;
      methodPaths?: Array<operations.MethodPaths> | undefined;
      languages?: Array<string> | undefined;
    }]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: [
      "@speakeasyapi/code-samples",
      "codeSamples",
      "get",
      ...queryKeyBase,
    ],
  });
}

export function invalidateAllCodeSamples(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["@speakeasyapi/code-samples", "codeSamples", "get"],
  });
}
