/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SpeakeasyCodeSamplesCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$codeSamplesGet } from "./tools/codeSamplesGet.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apiKey?: SDKOptions["apiKey"] | undefined;
  registryUrl?: SDKOptions["registryUrl"] | undefined;
  server?: SDKOptions["server"] | undefined;
}) {
  const server = new McpServer({
    name: "SpeakeasyCodeSamples",
    version: "2.4.0",
  });

  const client = new SpeakeasyCodeSamplesCore({
    apiKey: deps.apiKey,
    registryUrl: deps.registryUrl,
    serverURL: deps.serverURL,
    server: deps.server,
  });
  const scopes = new Set(deps.scopes ?? mcpScopes);
  const tool = createRegisterTool(deps.logger, server, client, scopes);

  tool(tool$codeSamplesGet);

  return server;
}
