/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Codesamples } from "./codesamples.js";

export class SDK extends ClientSDK {
  private _codesamples?: Codesamples;
  get codesamples(): Codesamples {
    return (this._codesamples ??= new Codesamples(this._options));
  }
}
