/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { CodeSamples } from "./codesamples.js";

export class SDK extends ClientSDK {
  private _codeSamples?: CodeSamples;
  get codeSamples(): CodeSamples {
    return (this._codeSamples ??= new CodeSamples(this._options));
  }
}
