/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @speakeasyapi/code-samples SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx codeSamplesGet.example.ts
 */

import { SpeakeasyCodeSamples } from "@speakeasyapi/code-samples";

const speakeasyCodeSamples = new SpeakeasyCodeSamples({
  registryUrl: "https://spec.speakeasy.com/my-org/my-workspace/my-source",
  apiKey: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await speakeasyCodeSamples.codeSamples.get({
    operationIds: [
      "g",
      "e",
      "t",
      "P",
      "e",
      "t",
      "s",
    ],
    methodPaths: [
      {
        method: "get",
        path: "/pets",
      },
    ],
    languages: [
      "python",
      "javascript",
    ],
  });

  console.log(result);
}

main().catch(console.error);
